import {
  MyUserDocument,
  MyUserQuery,
  MyUserQueryVariables,
} from "@/graphql/operations";
import { getUrqlClient } from "@/lib/urql";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getMyUser() {
  const { client } = getUrqlClient();
  const result = await client.query<MyUserQuery, MyUserQueryVariables>(
    MyUserDocument,
    {}
  );

  return result;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data, error } = await getMyUser();

  console.log(`MyUser ${data}`);

  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
